function a(e,t,n){var r=e,i=t.split("."),s;while(i.length>0){s=i.shift();if(!r[s]){if(i.length>0)r[s]={};else{r[s]=n}}r=r[s]}};
a(exports,"sdk.helper.class",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/helper/class.node.js"));
a(exports,"sdk.ioc",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/ioc.node.js"));
a(exports,"sdk.main",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/main.node.js"));
a(exports,"sdk.provider.logging",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/provider/logging.node.js"));
a(exports,"sdk.service.base",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/service/base.node.js"));
a(exports,"sdk.view-model.base",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/view-model/base.node.js"));
a(exports,"sdk.service.navigation",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/service/navigation.node.js"));
a(exports,"sdk.view-model.home",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/view-model/home.node.js"));
a(exports,"sdk.view-model.login",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/view-model/login.node.js"));
a(exports,"sdk.view-model.splash",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/view-model/splash.node.js"));
a(exports,"sdk.view.define",require("C:/src/DeepElement/MetroNode-Bootstrap/src/Shared/sdk/view/define.node.js"));
